select * from customer;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchased_amount)as total_revenue from customer group by gender order by gender asc;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchased_amount from customer where discount_applied='Yes' and
purchased_amount>=(select avg(purchased_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating)::numeric,2) as avg_review 
from customer
group by item_purchased 
order by avg_review desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,Round(avg(purchased_amount),2) from customer where 
shipping_type in ('Express','Standard') group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(subscription_status) as total_number,
round(avg(purchased_amount),2) as total_spent,
sum(purchased_amount) as total_revenue
 from customer 
 group by subscription_status
 order by total_spent desc, total_revenue desc;

--  A. No,their average spending is the same irrespective of the subscription but total revenue
-- is more in unsubscribed people
 
 --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
with cte as( select item_purchased,sum(purchased_amount)as total_amount,
 sum(case 
 when discount_applied='Yes' then purchased_amount else 0 end) as total_discounted_amount
 from customer
 group by item_purchased
)
select item_purchased,total_amount,total_discounted_amount,
round(total_discounted_amount/total_amount *100,2) as discount_percentage from cte
order by discount_percentage desc limit 5 ;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as(
select customer_id,
case when previous_purchases<=1 then 'New'
     when previous_purchases<=10 then 'Returning'
	 else 'Loyal'
	 end as loyalty
	 from customer)
select Loyalty, count(customer_id)as total_customers from cte group by loyalty 
--Q8. What are the top 3 most purchased products within each category? 
with cte as (select item_purchased,category,count(item_purchased) as purchased_quantity,
Row_number () over(partition by category order by count(item_purchased)desc )as item_rank
from customer
group by category,item_purchased
)
select Category,item_purchased as items, purchased_quantity from cte where item_rank<=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    previous_purchases > 5 AS is_repeat_buyer,
   round( AVG(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100 ,2)
        AS subscription_rate
FROM customer
GROUP BY is_repeat_buyer;

SELECT  CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type, count(*) as total_customers,
	round(100*avg(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END),2) as subscribed_count	
FROM customer
GROUP BY buyer_type;


--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchased_amount) as revenue from customer
group by age_group
order by revenue desc;

